//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketSysteemMVC5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public System.DateTime Datum { get; set; }
        public string Onderwerp { get; set; }
        public string Omschrijving { get; set; }
        public int Status { get; set; }
        public int Applicatie_Id { get; set; }
        public string Klant_Id { get; set; }
    
        public virtual Applicaty Applicaty { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
